# Generated by Django 5.2 on 2026-01-04 18:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='orderID',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.ImageField(blank=True, default='profile/default_user.png', null=True, upload_to=base.models.nameAndOverwriteReviewImage),
        ),
    ]
